# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2fb04d624b06d40ac1b743856994e1220fcd790d4540caf2d933a81c7f708f30923cedbe118a7529ce14ca4d5bd9209d888356cede9e8fb87fa2c49714ce563

test:
  secret_key_base: 8b3e8e8b91d5d4bb6749fcbc7509cf272a7dd5594ec9c989b481ce176b50289522eedf2038c90fdc8d2a269d94a3986fa3c2fb167dbaa36d97681cc0a2fef031

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
